# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Crud.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_crud(object):
    def setupUi(self, crud):
        crud.setObjectName("crud")
        crud.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(crud)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(30, 350, 741, 211))
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 200, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 101, 17))
        self.label_3.setObjectName("label_3")
        self.cbBoxRole = QtWidgets.QComboBox(self.centralwidget)
        self.cbBoxRole.setGeometry(QtCore.QRect(50, 230, 261, 25))
        self.cbBoxRole.setObjectName("cbBoxRole")
        self.cbBoxRole.addItem("")
        self.cbBoxRole.addItem("")
        self.cbBoxRole.addItem("")
        self.btnCreate = QtWidgets.QPushButton(self.centralwidget)
        self.btnCreate.setGeometry(QtCore.QRect(180, 290, 111, 25))
        self.btnCreate.setObjectName("btnCreate")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(50, 70, 261, 25))
        self.inputName.setObjectName("inputName")
        self.inputLastName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputLastName.setGeometry(QtCore.QRect(50, 150, 261, 25))
        self.inputLastName.setObjectName("inputLastName")
        self.btnEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(340, 290, 121, 25))
        self.btnEdit.setObjectName("btnEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 70, 121, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(500, 290, 121, 25))
        self.btnDelete.setObjectName("btnDelete")
        crud.setCentralWidget(self.centralwidget)

        self.btnEdit.clicked.connect(self._handleEdit)
        self.btnCreate.clicked.connect(self._handleCreate)
        self.btnDelete.clicked.connect(self._handleDelete)
        self.pushButton_3.clicked.connect(self._handleClean)

        self.retranslateUi(crud)
        QtCore.QMetaObject.connectSlotsByName(crud)

    def _handleEdit(self):
        valueName = str(self.inputName.text())
        valueLastName = str(self.inputLastName.text())
        valueCbBoxRole = str(self.cbBoxRole.currentText())
        if valueName == "" or valueLastName == "":
            print("Please charge name and last name")
        else:
            self.listWidget.takeItem(self.listWidget.currentRow())
            self.listWidget.addItem(str(valueName + "   " + valueLastName + "   " + valueCbBoxRole))
        self.inputName.setText(str(""))
        self.inputLastName.setText(str(""))

    def _handleDelete(self):
        self.listWidget.takeItem(self.listWidget.currentRow())

    def _handleClean(self):
        self.inputName.setText(str(""))
        self.inputLastName.setText(str(""))

    def _handleCreate(self):
        valueName = str(self.inputName.text())
        valueLastName = str(self.inputLastName.text())
        valueCbBoxRole = str(self.cbBoxRole.currentText())
        if valueName == "" or valueLastName == "":
            print("Please charge name and last name")
        else:
            self.listWidget.addItem(str(valueName + "   " + valueLastName + "   " + valueCbBoxRole))
        self.inputName.setText(str(""))
        self.inputLastName.setText(str(""))


    def retranslateUi(self, crud):
        _translate = QtCore.QCoreApplication.translate
        crud.setWindowTitle(_translate("crud", "CRUD Users"))
        self.label.setText(_translate("crud", "Role"))
        self.label_2.setText(_translate("crud", "Name"))
        self.label_3.setText(_translate("crud", "LastName"))
        self.cbBoxRole.setItemText(0, _translate("crud", "Admin"))
        self.cbBoxRole.setItemText(1, _translate("crud", "User"))
        self.cbBoxRole.setItemText(2, _translate("crud", "Invitate"))
        self.btnCreate.setText(_translate("crud", "Create"))
        self.btnEdit.setText(_translate("crud", "Edit"))
        self.pushButton_3.setText(_translate("crud", "Clean"))
        self.btnDelete.setText(_translate("crud", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    crud = QtWidgets.QMainWindow()
    ui = Ui_crud()
    ui.setupUi(crud)
    crud.show()
    sys.exit(app.exec_())
