# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Welcome import Ui_WindowWelcome
class Ui_WindowLogin(object):

    def openWindowWelcome(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_WindowWelcome()
        self.ui.setupUi (self.window)
        #window.hide()
        self.window.show()

    def setupUi(self, WindowLogin):
        WindowLogin.setObjectName("WindowLogin")
        WindowLogin.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(WindowLogin)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.btnLogin.setGeometry(QtCore.QRect(300, 260, 191, 25))
        self.btnLogin.setObjectName("btnLogin")
        self.lblwelcome = QtWidgets.QLabel(self.centralwidget)
        self.lblwelcome.setGeometry(QtCore.QRect(290, 40, 211, 17))
        self.lblwelcome.setObjectName("lblwelcome")
        self.inputUser = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUser.setGeometry(QtCore.QRect(270, 110, 241, 25))
        self.inputUser.setText("")
        self.inputUser.setObjectName("inputUser")
        self.inputPass = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPass.setGeometry(QtCore.QRect(270, 160, 241, 25))
        self.inputPass.setText("")
        self.inputPass.setObjectName("inputPass")
        WindowLogin.setCentralWidget(self.centralwidget)

        self.btnLogin.clicked.connect(self.openWindowWelcome)

        self.retranslateUi(WindowLogin)
        QtCore.QMetaObject.connectSlotsByName(WindowLogin)

    def retranslateUi(self, WindowLogin):
        _translate = QtCore.QCoreApplication.translate
        WindowLogin.setWindowTitle(_translate("WindowLogin", "Login interface"))
        self.btnLogin.setText(_translate("WindowLogin", "Login"))
        self.lblwelcome.setText(_translate("WindowLogin", "Welcome to Login Interface"))
        self.btnLogin.setText(_translate("window", "Login"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowLogin = QtWidgets.QMainWindow()
    ui = Ui_WindowLogin()
    ui.setupUi(WindowLogin)
    WindowLogin.show()
    sys.exit(app.exec_())
