# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from OtherWindow import Ui_OtherWindow

class Ui_window(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_OtherWindow()
        self.ui.setupUi (self.window)
        window.hide()
        self.window.show()

    def setupUi(self, window):
        window.setObjectName("window")
        window.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setObjectName("centralwidget")
        self.add = QtWidgets.QPushButton(self.centralwidget)
        self.add.setGeometry(QtCore.QRect(530, 180, 80, 25))
        self.add.setObjectName("add")
        self.subtract = QtWidgets.QPushButton(self.centralwidget)
        self.subtract.setGeometry(QtCore.QRect(640, 180, 80, 25))
        self.subtract.setObjectName("subtract")
        self.ticket = QtWidgets.QLabel(self.centralwidget)
        self.ticket.setGeometry(QtCore.QRect(620, 100, 16, 17))
        self.ticket.setObjectName("ticket")
        self.btn_open = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(130, 350, 191, 25))
        self.btn_open.setObjectName("btn_open")
        window.setCentralWidget(self.centralwidget)
        self.add.clicked.connect(self.add_click)
        self.add.clicked.connect(self.print_click)
        self.subtract.clicked.connect(self.print_click_subtract)
        self.subtract.clicked.connect(self.down_click)

        self.btn_open.clicked.connect(self.openWindow)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, window):
        _translate = QtCore.QCoreApplication.translate
        window.setWindowTitle(_translate("window", "Main window xd"))
        self.add.setText(_translate("window", "add"))
        self.subtract.setText(_translate("window", "subtract"))
        self.ticket.setText(_translate("window", "1"))
        self.btn_open.setText(_translate("window", "Open window 1"))

    def print_click(self):
        print("click!")
    def print_click_subtract(self):
        print("se resto!")

    def add_click(self):
        value = int(self.ticket.text())
        values = 1
        self.ticket.setText(str(values + value))
    def down_click(self):
        value = int(self.ticket.text())
        values = -1
        self.ticket.setText(str(values + value))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = QtWidgets.QMainWindow()
    ui = Ui_window()
    ui.setupUi(window)
    window.show()
    sys.exit(app.exec_())
