# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WindowWelcome(object):
    def setupUi(self, WindowWelcome):
        WindowWelcome.setObjectName("WindowWelcome")
        WindowWelcome.resize(516, 541)
        self.centralwidget = QtWidgets.QWidget(WindowWelcome)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 20, 91, 61))
        self.label.setObjectName("label")
        WindowWelcome.setCentralWidget(self.centralwidget)

        self.retranslateUi(WindowWelcome)
        QtCore.QMetaObject.connectSlotsByName(WindowWelcome)

    def retranslateUi(self, WindowWelcome):
        _translate = QtCore.QCoreApplication.translate
        WindowWelcome.setWindowTitle(_translate("WindowWelcome", "WELCOME"))
        self.label.setText(_translate("WindowWelcome", "WELCOME"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WindowWelcome = QtWidgets.QMainWindow()
    ui = Ui_WindowWelcome()
    ui.setupUi(WindowWelcome)
    WindowWelcome.show()
    sys.exit(app.exec_())
